sudo: required
dist: trusty

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                        - llvm-toolchain-precise-3.6
                packages:
                        - gcc-5
                        - g++-5
                        - clang-3.6        

language: c

compiler:
        - gcc

before_install: ./autogen.sh
install: ./configure && make && make check

